import React, { useState } from 'react';
import type { GeneratedPrompt } from '../../types/prompt';
import './PromptResult.css';

interface PromptResultProps {
    prompt: GeneratedPrompt;
    onSave: (prompt: GeneratedPrompt) => void;
    isSaved: boolean;
}

function copyToClipboard(text: string): Promise<void> {
    if (navigator.clipboard) {
        return navigator.clipboard.writeText(text);
    }
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    return Promise.resolve();
}

function exportTxt(prompt: GeneratedPrompt) {
    const content = [
        `# ${prompt.title}`,
        `# Generated by Umbra Prompt Lab — ${new Date(prompt.createdAt).toLocaleString()}`,
        '',
        '## MAIN PROMPT',
        prompt.mainPrompt,
        '',
        '## NEGATIVE PROMPT',
        prompt.negativePrompt,
        '',
        '## QUICK PROMPT',
        prompt.quickPrompt,
        '',
        '## PARAMETERS',
        `Steps: ${prompt.parameters.steps}`,
        `CFG Scale: ${prompt.parameters.cfg}`,
        `Sampler: ${prompt.parameters.sampler}`,
        `Resolution: ${prompt.parameters.width} x ${prompt.parameters.height}`,
        prompt.parameters.denoise != null ? `Denoise: ${prompt.parameters.denoise}` : '',
        '',
        '## ORIGINAL IDEA',
        prompt.originalIdea,
    ].filter(line => line !== undefined).join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `umbra_${prompt.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export const PromptResult: React.FC<PromptResultProps> = ({ prompt, onSave, isSaved }) => {
    const [copiedField, setCopiedField] = useState<string | null>(null);

    const handleCopy = async (text: string, field: string) => {
        try {
            await copyToClipboard(text);
            setCopiedField(field);
            setTimeout(() => setCopiedField(null), 2000);
        } catch {
            // silently fail
        }
    };

    return (
        <div className="prompt-result fade-in-scale">
            {/* Header */}
            <div className="result-header">
                <div className="result-title-area">
                    <span className="result-sparkle">✦</span>
                    <h2 className="result-title font-title">{prompt.title}</h2>
                </div>
                <div className="result-meta">
                    <span className="tag">{prompt.style}</span>
                    <span className="tag">{prompt.mood}</span>
                </div>
            </div>

            {/* Main Prompt */}
            <div className="result-block main-prompt-block">
                <div className="block-header">
                    <span className="block-label">✦ Prompt Principal</span>
                    <button
                        className="btn-ghost copy-btn"
                        onClick={() => handleCopy(prompt.mainPrompt, 'main')}
                        id="copy-main-prompt"
                    >
                        {copiedField === 'main' ? '✓ Copiado!' : '⎘ Copiar'}
                    </button>
                </div>
                <div className="block-content prompt-text" id="main-prompt-text">
                    {prompt.mainPrompt}
                </div>
            </div>

            {/* Negative Prompt */}
            <div className="result-block negative-prompt-block">
                <div className="block-header">
                    <span className="block-label neg-label">✕ Prompt Negativo</span>
                    <button
                        className="btn-ghost copy-btn"
                        onClick={() => handleCopy(prompt.negativePrompt, 'neg')}
                        id="copy-negative-prompt"
                    >
                        {copiedField === 'neg' ? '✓ Copiado!' : '⎘ Copiar'}
                    </button>
                </div>
                <div className="block-content neg-text" id="negative-prompt-text">
                    {prompt.negativePrompt}
                </div>
            </div>

            {/* Parameters */}
            <div className="result-block params-block">
                <div className="block-header">
                    <span className="block-label">⚙ Parâmetros Sugeridos</span>
                </div>
                <div className="params-grid">
                    <div className="param-item">
                        <span className="param-label">Steps</span>
                        <span className="param-value">{prompt.parameters.steps}</span>
                    </div>
                    <div className="param-item">
                        <span className="param-label">CFG Scale</span>
                        <span className="param-value">{prompt.parameters.cfg}</span>
                    </div>
                    <div className="param-item">
                        <span className="param-label">Sampler</span>
                        <span className="param-value">{prompt.parameters.sampler}</span>
                    </div>
                    <div className="param-item">
                        <span className="param-label">Resolução</span>
                        <span className="param-value">{prompt.parameters.width} × {prompt.parameters.height}</span>
                    </div>
                    {prompt.parameters.denoise != null && (
                        <div className="param-item">
                            <span className="param-label">Denoise</span>
                            <span className="param-value">{prompt.parameters.denoise}</span>
                        </div>
                    )}
                </div>
            </div>

            {/* Quick Prompt */}
            <div className="result-block quick-block">
                <div className="block-header">
                    <span className="block-label quick-label">⚡ Quick Prompt</span>
                    <button
                        className="btn-ghost copy-btn"
                        onClick={() => handleCopy(prompt.quickPrompt, 'quick')}
                        id="copy-quick-prompt"
                    >
                        {copiedField === 'quick' ? '✓ Copiado!' : '⎘ Copiar'}
                    </button>
                </div>
                <div className="block-content quick-text" id="quick-prompt-text">
                    {prompt.quickPrompt}
                </div>
            </div>

            {/* Actions */}
            <div className="result-actions">
                <button
                    className={`btn-ghost action-btn ${isSaved ? 'saved' : ''}`}
                    onClick={() => onSave(prompt)}
                    id="save-prompt-btn"
                    disabled={isSaved}
                >
                    {isSaved ? '✓ Salvo' : '★ Salvar'}
                </button>
                <button
                    className="btn-ghost action-btn"
                    onClick={() => handleCopy(`${prompt.mainPrompt}\n\nNegative: ${prompt.negativePrompt}`, 'all')}
                    id="copy-all-btn"
                >
                    {copiedField === 'all' ? '✓ Copiado!' : '⎘ Copiar Tudo'}
                </button>
                <button
                    className="btn-ghost action-btn"
                    onClick={() => exportTxt(prompt)}
                    id="export-txt-btn"
                >
                    ↓ Export .TXT
                </button>
            </div>
        </div>
    );
};
